version: "3.4"
services:
  stripe:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
    env_file: .env
    command: ./manage.py runserver 0.0.0.0:8000
  
  postgres:
    image: postgres:latest
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data: {}