# Generated by Django 3.2.9 on 2021-11-19 00:14

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentItent',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
            ],
        ),
    ]
