# Generated by Django 3.2.9 on 2021-11-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentItent',
            new_name='PaymentIntent',
        ),
    ]
