# Generated by Django 3.2.9 on 2021-12-28 22:38

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_paymentitent_paymentintent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
            ],
        ),
    ]
