# Generated by Django 3.2.9 on 2021-12-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_dispute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
