# Generated by Django 3.2.9 on 2022-01-03 18:36

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_paymentintent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
            ],
            options={
                'ordering': ['data__created'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
            ],
            options={
                'ordering': ['data__created'],
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['data__created']},
        ),
        migrations.AlterModelOptions(
            name='dispute',
            options={'ordering': ['data__created']},
        ),
        migrations.AlterModelOptions(
            name='paymentintent',
            options={'ordering': ['data__created']},
        ),
    ]
