# Generated by Django 3.2.9 on 2022-01-03 23:57

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20220103_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupIntent',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
            ],
            options={
                'ordering': ['-data__created'],
            },
        ),
        migrations.AlterModelOptions(
            name='charge',
            options={'ordering': ['-data__created']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-data__created']},
        ),
        migrations.AlterModelOptions(
            name='dispute',
            options={'ordering': ['-data__created']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-data__created']},
        ),
        migrations.AlterModelOptions(
            name='paymentintent',
            options={'ordering': ['-data__created']},
        ),
    ]
