# Generated by Django 3.2.9 on 2022-01-06 15:15

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_price_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
            ],
            options={
                'ordering': ['-data__created'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-data__created']},
        ),
    ]
