# Generated by Django 3.2.9 on 2022-06-15 20:49

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_location_reader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
            ],
            options={
                'ordering': ['-data__created'],
            },
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-data__created']},
        ),
        migrations.AlterModelOptions(
            name='reader',
            options={'ordering': ['-data__created']},
        ),
    ]
