# Generated by Django 3.2.9 on 2022-07-05 20:07

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_auto_20220615_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='automatic_payment_methods',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='charges',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='client_secret',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='currency',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='customer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='last_payment_error',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='metadata',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='next_action',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='payment_method',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='payment_method_types',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='receipt_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='setup_future_usage',
            field=models.CharField(choices=[('off_session', 'off session'), ('on_session', 'on session')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='shipping',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='statement_descriptor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='statement_descriptor_suffix',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
