# Generated by Django 3.2.9 on 2022-09-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_stripeaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeaccount',
            name='country',
            field=models.CharField(help_text='ISO 2-letter abbreviation for country', max_length=2, null=True),
        ),
    ]
