# Generated by Django 3.2.9 on 2022-09-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_stripeaccount_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeaccount',
            name='account_id',
            field=models.CharField(blank=True, help_text='Account ID from Stripe', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stripeaccount',
            name='country',
            field=models.CharField(blank=True, help_text='ISO 2-letter abbreviation for country', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='stripeaccount',
            name='live_private_api_key',
            field=models.CharField(blank=True, help_text='Live mode server-side API key', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stripeaccount',
            name='live_public_api_key',
            field=models.CharField(blank=True, help_text='Live mode client-side API key', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stripeaccount',
            name='name',
            field=models.CharField(blank=True, help_text='Friendly name for this account', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='stripeaccount',
            name='test_private_api_key',
            field=models.CharField(blank=True, help_text='Test mode server-side API key', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stripeaccount',
            name='test_public_api_key',
            field=models.CharField(blank=True, help_text='Test mode client-side API key', max_length=255, null=True),
        ),
    ]
