# Generated by Django 3.2.9 on 2022-09-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_auto_20220902_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripeaccount',
            old_name='live_private_api_key',
            new_name='Live Private Key',
        ),
        migrations.RenameField(
            model_name='stripeaccount',
            old_name='live_public_api_key',
            new_name='Live Public Key',
        ),
        migrations.RenameField(
            model_name='stripeaccount',
            old_name='test_private_api_key',
            new_name='Test Private Key',
        ),
        migrations.RenameField(
            model_name='stripeaccount',
            old_name='test_public_api_key',
            new_name='Test Public Key',
        ),
        migrations.AddField(
            model_name='stripeaccount',
            name='has_connect',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripeaccount',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'United States of America'), ('CA', 'Canada'), ('MX', 'Mexico'), ('DE', 'Germany'), ('FR', 'France')], help_text='ISO 2-letter abbreviation for country', max_length=2, null=True),
        ),
    ]
