# Generated by Django 3.2.9 on 2022-09-27 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_auto_20220902_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stripe_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='payments.stripeaccount'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='stripe_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='payments.stripeaccount'),
        ),
        migrations.AlterField(
            model_name='stripeaccount',
            name='has_connect',
            field=models.BooleanField(help_text='Whether this account is a platform with Connect Accounts associated'),
        ),
    ]
