# Generated by Django 3.2.9 on 2023-01-19 00:45

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_appaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestClock',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
            ],
            options={
                'ordering': ['-data__created'],
            },
        ),
    ]
